# Generated by Django 6.0.3 on 2026-03-27 13:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        max_length=6,
                        unique=True,
                        verbose_name="Код мероприятия",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Место проведения"
                    ),
                ),
                (
                    "organizer_contacts",
                    models.TextField(blank=True, verbose_name="Контакты организатора"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Начало")),
                ("end_time", models.DateTimeField(verbose_name="Конец")),
                (
                    "is_open",
                    models.BooleanField(
                        default=False,
                        help_text="Управляется вручную. Celery Beat автоматически закрывает по end_time.",
                        verbose_name="Открыто",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Используется для немедленной инвалидации JWT токенов.",
                        null=True,
                        verbose_name="Время закрытия",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Организатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login",
                    models.EmailField(max_length=254, verbose_name="Email (логин)"),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Хэш пароля"
                    ),
                ),
                (
                    "password_encrypted",
                    models.BinaryField(
                        blank=True,
                        null=True,
                        verbose_name="Зашифрованный пароль (для орга)",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Telegram ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "role",
                    models.CharField(
                        choices=[("guest", "Гость"), ("staff", "Персонал")],
                        default="guest",
                        max_length=10,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="True = заблокирован, False = активен",
                        verbose_name="Заблокирован",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="api.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь мероприятия",
                "verbose_name_plural": "Пользователи мероприятий",
            },
        ),
        migrations.CreateModel(
            name="GuestRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название роли"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_roles",
                        to="api.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль гостя",
                "verbose_name_plural": "Роли гостей",
            },
        ),
        migrations.CreateModel(
            name="EventGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="api.event",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "event_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_profile",
                        to="api.eventuser",
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guests",
                        to="api.guestrole",
                        verbose_name="Роль гостя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Гость мероприятия",
                "verbose_name_plural": "Гости мероприятий",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название меню"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="api.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="0 = бесплатно в рамках лимитов роли",
                        max_digits=8,
                        verbose_name="Цена",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu-items/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.menu",
                        verbose_name="Меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция меню",
                "verbose_name_plural": "Позиции меню",
            },
        ),
        migrations.CreateModel(
            name="GuestRoleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимальное количество",
                    ),
                ),
                (
                    "discount_pct",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="100 = бесплатно",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Скидка (%)",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_items",
                        to="api.guestrole",
                        verbose_name="Роль",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_limits",
                        to="api.menuitem",
                        verbose_name="Позиция меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лимит позиции для роли",
                "verbose_name_plural": "Лимиты позиций для ролей",
            },
        ),
        migrations.CreateModel(
            name="GuestLimitUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Использовано (hold + выдано)"
                    ),
                ),
                (
                    "event_guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limit_usages",
                        to="api.eventguest",
                        verbose_name="Гость",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_usages",
                        to="api.menuitem",
                        verbose_name="Позиция меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Использование лимита",
                "verbose_name_plural": "Использование лимитов",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("preparing", "Готовится"),
                            ("ready", "Готов"),
                            ("completed", "Выдан"),
                            ("cancelled", "Отменён"),
                            ("modified", "Изменён"),
                        ],
                        default="created",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        help_text="Формат: TECH24-KFN-007",
                        max_length=30,
                        unique=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "cancel_note",
                    models.TextField(blank=True, verbose_name="Причина отмены"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="api.event",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="api.eventuser",
                        verbose_name="Гость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Текст уведомления")),
                (
                    "order_status",
                    models.CharField(
                        max_length=15,
                        verbose_name="Статус заказа на момент уведомления",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.eventuser",
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "removed",
                    models.BooleanField(
                        default=False,
                        help_text="Устанавливается при стоп-листе или ручной модификации",
                        verbose_name="Убрана из заказа",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="api.menuitem",
                        verbose_name="Позиция меню",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
            },
        ),
        migrations.CreateModel(
            name="OrganizerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Организатор",
                "verbose_name_plural": "Организаторы",
            },
        ),
        migrations.CreateModel(
            name="Stall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "abbr",
                    models.CharField(
                        help_text="3 символа для номера заказа, например KFN для Кофейня",
                        max_length=3,
                        verbose_name="Аббревиатура",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыта"), ("closed", "Закрыта")],
                        default="closed",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stalls",
                        to="api.event",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stalls",
                        to="api.menu",
                        verbose_name="Меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка выдачи",
                "verbose_name_plural": "Точки выдачи",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="stall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.stall",
                verbose_name="Точка выдачи",
            ),
        ),
        migrations.CreateModel(
            name="StallMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="False = в стоп-листе на этой точке",
                        verbose_name="Доступно",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stall_items",
                        to="api.menuitem",
                        verbose_name="Позиция меню",
                    ),
                ),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stall_items",
                        to="api.stall",
                        verbose_name="Точка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступность позиции на точке",
                "verbose_name_plural": "Стоп-лист точек",
            },
        ),
        migrations.CreateModel(
            name="StallStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to="api.eventuser",
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="api.stall",
                        verbose_name="Точка выдачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонал точки",
                "verbose_name_plural": "Персонал точек",
            },
        ),
        migrations.AddConstraint(
            model_name="eventuser",
            constraint=models.UniqueConstraint(
                fields=("event", "login"), name="unique_event_login"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telegram_id__isnull", False)),
                fields=("event", "telegram_id"),
                name="unique_event_telegram_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("password_hash__isnull", False),
                    ("telegram_id__isnull", False),
                    _connector="OR",
                ),
                name="event_user_has_credentials",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="guestrole",
            unique_together={("event", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="guestroleitem",
            unique_together={("role", "menu_item")},
        ),
        migrations.AlterUniqueTogether(
            name="guestlimitusage",
            unique_together={("event_guest", "menu_item")},
        ),
        migrations.AlterUniqueTogether(
            name="stall",
            unique_together={("event", "abbr")},
        ),
        migrations.AlterUniqueTogether(
            name="stallmenuitem",
            unique_together={("stall", "menu_item")},
        ),
        migrations.AddConstraint(
            model_name="stallstaff",
            constraint=models.UniqueConstraint(
                fields=("event_user",), name="unique_staff_per_user"
            ),
        ),
    ]
