# Generated by Django 6.0.3 on 2026-03-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventuser",
            name="unique_event_login",
        ),
        migrations.RemoveConstraint(
            model_name="eventuser",
            name="event_user_has_credentials",
        ),
        migrations.AddField(
            model_name="eventuser",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                help_text="@username в Telegram. Орг добавляет по username.",
                max_length=255,
                null=True,
                verbose_name="Telegram username",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="eventuser",
            name="login",
            field=models.EmailField(
                blank=True,
                help_text="Email для входа по паролю. Обязательно если нет telegram_username.",
                max_length=254,
                null=True,
                verbose_name="Email (логин)",
            ),
        ),
        migrations.AlterField(
            model_name="eventuser",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Заполняется автоматически ботом при первом входе.",
                null=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("login__isnull", False)),
                fields=("event", "login"),
                name="unique_event_login",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telegram_username__isnull", False)),
                fields=("event", "telegram_username"),
                name="unique_event_telegram_username",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventuser",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("login__isnull", False),
                    ("telegram_username__isnull", False),
                    _connector="OR",
                ),
                name="event_user_has_primary_identifier",
            ),
        ),
    ]
