# Generated by Django 5.x on 2026-03-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_eventuser_unique_event_login_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="menu-item-gallery/", verbose_name="Фото"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.menuitem",
                        verbose_name="Позиция меню",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_menu_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото позиции меню",
                "verbose_name_plural": "Фото позиций меню",
                "ordering": ["-created_at"],
            },
        ),
    ]
