# Generated by Django 5.x on 2026-03-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_menuimage"),
    ]

    operations = [
        migrations.DeleteModel(name="MenuImage"),
    ]
